# Generated by Django 4.1.1 on 2022-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beforelogin', '0002_rename_email_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
