# Generated by Django 4.1.1 on 2022-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beforelogin', '0003_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
